//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.Application.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class BasicProductLimit
    {
        public int id { get; set; }
        public string BasicProductLimitCode { get; set; }
        public string BasicProductId { get; set; }
        public string BenefitCode { get; set; }
        public string LimitType { get; set; }
        public Nullable<int> LimitNumber { get; set; }
        public Nullable<decimal> LimitAmount { get; set; }
        public Nullable<int> Pre { get; set; }
        public Nullable<int> Post { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<short> IsActive { get; set; }
    
        public virtual BasicProduct BasicProduct { get; set; }
        public virtual Benefit Benefit { get; set; }
    }
}
