//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.Application.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Endorsement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Endorsement()
        {
            this.Endorsement1 = new HashSet<Endorsement>();
            this.Member_Endorse = new HashSet<Member_Endorse>();
            this.Member_Movement = new HashSet<Member_Movement>();
            this.MemberPlan_Endorse = new HashSet<MemberPlan_Endorse>();
            this.MemberPlan_H = new HashSet<MemberPlan_H>();
            this.PCF_Endorse = new HashSet<PCF_Endorse>();
            this.PlanDetail_Endorse = new HashSet<PlanDetail_Endorse>();
            this.Plan_Endorse = new HashSet<Plan_Endorse>();
        }
    
        public int Id { get; set; }
        public string EndorseNumber { get; set; }
        public string EndorseParent { get; set; }
        public Nullable<System.DateTime> EndorseDate { get; set; }
        public string PolicyId { get; set; }
        public string PolicyNumber { get; set; }
        public string EndorseType { get; set; }
        public string EndorseNotes { get; set; }
        public Nullable<System.DateTime> CompletedDate { get; set; }
        public string EndorseStatus { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<short> IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Endorsement> Endorsement1 { get; set; }
        public virtual Endorsement Endorsement2 { get; set; }
        public virtual Policy Policy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Member_Endorse> Member_Endorse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Member_Movement> Member_Movement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MemberPlan_Endorse> MemberPlan_Endorse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MemberPlan_H> MemberPlan_H { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PCF_Endorse> PCF_Endorse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlanDetail_Endorse> PlanDetail_Endorse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Plan_Endorse> Plan_Endorse { get; set; }
        public virtual Policy_Endorse Policy_Endorse { get; set; }
    }
}
