//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.Application.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinanceTransaction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FinanceTransaction()
        {
            this.FinanceTransactionDetail = new HashSet<FinanceTransactionDetail>();
        }
    
        public long ID { get; set; }
        public int RecordMode { get; set; }
        public string TransactionNumber { get; set; }
        public string TransactionBranch { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public string TransCodeId { get; set; }
        public string DCN_Number { get; set; }
        public Nullable<System.DateTime> ProcessDate { get; set; }
        public string ReferenceNumber { get; set; }
        public string PolicyId { get; set; }
        public string PolicyNumber { get; set; }
        public Nullable<System.DateTime> ReconDate { get; set; }
        public string ReconNumber { get; set; }
        public string ReconStatus { get; set; }
        public Nullable<decimal> OutstandingAmount { get; set; }
        public string BankId { get; set; }
        public string BankAccountNumber { get; set; }
        public string BankCurrency { get; set; }
        public Nullable<decimal> TransExchangeRate { get; set; }
        public Nullable<decimal> TransactionAmount { get; set; }
        public string ClientId { get; set; }
        public string ClientBankId { get; set; }
        public string ClientAccountNumber { get; set; }
        public string ClientAccountName { get; set; }
        public string ClientCurrency { get; set; }
        public Nullable<decimal> ClientTransExchangeRate { get; set; }
        public Nullable<decimal> ClientTransactionAmount { get; set; }
        public string ClosingAgen { get; set; }
        public string DebitCOA { get; set; }
        public string CreditCOA { get; set; }
        public string ReconCOA { get; set; }
        public string TransDescription { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<short> IsActive { get; set; }
    
        public virtual Policy Policy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FinanceTransactionDetail> FinanceTransactionDetail { get; set; }
    }
}
