//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.Application.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinanceTransactionDetail
    {
        public long ID { get; set; }
        public string TransactionNumber { get; set; }
        public string BasicProductId { get; set; }
        public Nullable<decimal> OutstandingAmount { get; set; }
        public Nullable<decimal> TransactionAmount { get; set; }
        public Nullable<decimal> BankAmount { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<short> IsActive { get; set; }
    
        public virtual BasicProduct BasicProduct { get; set; }
        public virtual FinanceTransaction FinanceTransaction { get; set; }
    }
}
