//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.Application.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plan_Endorse
    {
        public string EndorseNumber { get; set; }
        public string PolicyId { get; set; }
        public string PlanId { get; set; }
        public string PlanName { get; set; }
        public string PlanDesc { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<short> IsActive { get; set; }
    
        public virtual Endorsement Endorsement { get; set; }
        public virtual Policy Policy { get; set; }
    }
}
