//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.Application.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Policy_Endorse
    {
        public string EndorseNumber { get; set; }
        public string PolicyId { get; set; }
        public string PolicyNumber { get; set; }
        public string ClientId { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> MatureDate { get; set; }
        public Nullable<System.DateTime> LastEndorseDate { get; set; }
        public Nullable<System.DateTime> ExitDate { get; set; }
        public Nullable<System.DateTime> TerminateDate { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public string PaymentFrequency { get; set; }
        public string OpenOrClose { get; set; }
        public string Agent { get; set; }
        public string PolicyStatus { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<short> IsActive { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Endorsement Endorsement { get; set; }
        public virtual Policy Policy { get; set; }
    }
}
