//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.Application.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PremiumRate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PremiumRate()
        {
            this.PremiumRateDetails = new HashSet<PremiumRateDetails>();
        }
    
        public string InsurerId { get; set; }
        public string ScheduleId { get; set; }
        public string ActuaryId { get; set; }
        public long RateId { get; set; }
        public string RateType { get; set; }
        public string ClassOfRiskId { get; set; }
        public decimal PaymentDuration { get; set; }
        public decimal CoverageDuration { get; set; }
        public string PaymentFrequency { get; set; }
        public Nullable<decimal> Factor { get; set; }
        public string Name { get; set; }
        public string RecordStatus { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<short> IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PremiumRateDetails> PremiumRateDetails { get; set; }
    }
}
