//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.Application.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PremiumRateDetails
    {
        public long Id { get; set; }
        public long RateId { get; set; }
        public decimal PaymentDuration { get; set; }
        public decimal CoverageDuration { get; set; }
        public string IsAdult { get; set; }
        public string Sex { get; set; }
        public string IsSmoking { get; set; }
        public decimal RangeUpMin { get; set; }
        public decimal RangeUpMax { get; set; }
        public decimal RangeAgeMin { get; set; }
        public decimal RangeAgeMax { get; set; }
        public Nullable<decimal> PremiumRate { get; set; }
        public string RecordStatus { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<short> IsActive { get; set; }
    
        public virtual PremiumRate PremiumRate1 { get; set; }
    }
}
